import Head from 'next/head';
import React from 'react';

import { Accounts, FAQ } from '../../features'
import { Container } from '@mantine/core';

export default function AccountsPage() {
  return (
    <>
      <Head>
      <title>Accounts | DeRafl - Decentralized NFT Raffles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta property="og:title" content="Accounts | DeRafl - Decentralized NFT Raffles"/>
        <meta property="og:description" content="DeRafl brings you the opportunity to win unique digital assets with our revolutionary decentrailized raffle protocol"/>
        <meta property="og:type" content="website"/>
        <meta property="og:image" content="https://derafl.com/meta.png"></meta>
        <meta name="twitter:site" content="@derafl_"></meta>
        <meta name="twitter:card" content="summary_large_image"></meta>
        <meta name="robots" content="index,follow"></meta>
      </Head>
      <main>
        <Container size="xl">
          <Accounts />
        </Container>
      </main>
    </>
  )
}
