/* tslint:disable */
/* eslint-disable */
// this is an auto generated file. This will be overwritten

import * as APITypes from "../API";
type GeneratedMutation<InputType, OutputType> = string & {
  __generatedMutationInput: InputType;
  __generatedMutationOutput: OutputType;
};

export const createTicketRefund = /* GraphQL */ `mutation CreateTicketRefund(
  $input: CreateTicketRefundInput!
  $condition: ModelTicketRefundConditionInput
) {
  createTicketRefund(input: $input, condition: $condition) {
    id
    type
    createdAt
    updatedAt
    raffleNonce
    ethAmount
    refundee
    chainId
    raffle {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      ticketsAvailable
      winningBatch {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        lastTicket
        transaction {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        purchaser
        ticketsBought
        batchId
        firstTicket
        chainId
        raffle {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          ticketsAvailable
          winningBatch {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            lastTicket
            purchaser
            ticketsBought
            batchId
            firstTicket
            chainId
            ticketBatchTransactionId
            ticketBatchRaffleId
            __typename
          }
          releaseTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          progress
          openTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          drawnTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          state
          tokenId
          expires
          nftAddress
          ticketsSold
          ticketBatches
          winningTicket
          closeTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          chainId
          winningAccount
          owner
          contract
          nft {
            id
            type
            createdAt
            updatedAt
            contractAddress
            metadata
            tokenUri
            tokenId
            symbol
            imageUri
            tokenName
            collectionName
            lastSales
            chainId
            rarityData
            nFTCollectionId
            __typename
          }
          refundTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          raffleWinningBatchId
          raffleReleaseTxId
          raffleOpenTxId
          raffleDrawnTxId
          raffleCloseTxId
          raffleNftId
          raffleRefundTxId
          __typename
        }
        ticketBatchTransactionId
        ticketBatchRaffleId
        __typename
      }
      releaseTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      progress
      openTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      drawnTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      state
      tokenId
      expires
      nftAddress
      ticketsSold
      ticketBatches
      winningTicket
      closeTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      chainId
      winningAccount
      owner
      contract
      nft {
        id
        type
        createdAt
        updatedAt
        contractAddress
        metadata
        tokenUri
        tokenId
        symbol
        imageUri
        tokenName
        collectionName
        lastSales
        chainId
        rarityData
        animationUrl
        collection {
          id
          type
          contractAddress
          createdAt
          updatedAt
          symbol
          rafflesCreated
          contractDeployer
          deployedBlockNumber
          tokenType
          totalSupply
          chainId
          name
          openseaSlug
          imageUrl
          externalUrl
          discordUrl
          twitterUsername
          description
          floorPrice
          __typename
        }
        nFTCollectionId
        __typename
      }
      refundTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      raffleWinningBatchId
      raffleReleaseTxId
      raffleOpenTxId
      raffleDrawnTxId
      raffleCloseTxId
      raffleNftId
      raffleRefundTxId
      __typename
    }
    tx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    ticketRefundRaffleId
    ticketRefundTxId
    __typename
  }
}
` as GeneratedMutation<
  APITypes.CreateTicketRefundMutationVariables,
  APITypes.CreateTicketRefundMutation
>;
export const updateTicketRefund = /* GraphQL */ `mutation UpdateTicketRefund(
  $input: UpdateTicketRefundInput!
  $condition: ModelTicketRefundConditionInput
) {
  updateTicketRefund(input: $input, condition: $condition) {
    id
    type
    createdAt
    updatedAt
    raffleNonce
    ethAmount
    refundee
    chainId
    raffle {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      ticketsAvailable
      winningBatch {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        lastTicket
        transaction {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        purchaser
        ticketsBought
        batchId
        firstTicket
        chainId
        raffle {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          ticketsAvailable
          winningBatch {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            lastTicket
            purchaser
            ticketsBought
            batchId
            firstTicket
            chainId
            ticketBatchTransactionId
            ticketBatchRaffleId
            __typename
          }
          releaseTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          progress
          openTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          drawnTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          state
          tokenId
          expires
          nftAddress
          ticketsSold
          ticketBatches
          winningTicket
          closeTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          chainId
          winningAccount
          owner
          contract
          nft {
            id
            type
            createdAt
            updatedAt
            contractAddress
            metadata
            tokenUri
            tokenId
            symbol
            imageUri
            tokenName
            collectionName
            lastSales
            chainId
            rarityData
            nFTCollectionId
            __typename
          }
          refundTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          raffleWinningBatchId
          raffleReleaseTxId
          raffleOpenTxId
          raffleDrawnTxId
          raffleCloseTxId
          raffleNftId
          raffleRefundTxId
          __typename
        }
        ticketBatchTransactionId
        ticketBatchRaffleId
        __typename
      }
      releaseTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      progress
      openTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      drawnTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      state
      tokenId
      expires
      nftAddress
      ticketsSold
      ticketBatches
      winningTicket
      closeTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      chainId
      winningAccount
      owner
      contract
      nft {
        id
        type
        createdAt
        updatedAt
        contractAddress
        metadata
        tokenUri
        tokenId
        symbol
        imageUri
        tokenName
        collectionName
        lastSales
        chainId
        rarityData
        animationUrl
        collection {
          id
          type
          contractAddress
          createdAt
          updatedAt
          symbol
          rafflesCreated
          contractDeployer
          deployedBlockNumber
          tokenType
          totalSupply
          chainId
          name
          openseaSlug
          imageUrl
          externalUrl
          discordUrl
          twitterUsername
          description
          floorPrice
          __typename
        }
        nFTCollectionId
        __typename
      }
      refundTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      raffleWinningBatchId
      raffleReleaseTxId
      raffleOpenTxId
      raffleDrawnTxId
      raffleCloseTxId
      raffleNftId
      raffleRefundTxId
      __typename
    }
    tx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    ticketRefundRaffleId
    ticketRefundTxId
    __typename
  }
}
` as GeneratedMutation<
  APITypes.UpdateTicketRefundMutationVariables,
  APITypes.UpdateTicketRefundMutation
>;
export const deleteTicketRefund = /* GraphQL */ `mutation DeleteTicketRefund(
  $input: DeleteTicketRefundInput!
  $condition: ModelTicketRefundConditionInput
) {
  deleteTicketRefund(input: $input, condition: $condition) {
    id
    type
    createdAt
    updatedAt
    raffleNonce
    ethAmount
    refundee
    chainId
    raffle {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      ticketsAvailable
      winningBatch {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        lastTicket
        transaction {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        purchaser
        ticketsBought
        batchId
        firstTicket
        chainId
        raffle {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          ticketsAvailable
          winningBatch {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            lastTicket
            purchaser
            ticketsBought
            batchId
            firstTicket
            chainId
            ticketBatchTransactionId
            ticketBatchRaffleId
            __typename
          }
          releaseTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          progress
          openTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          drawnTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          state
          tokenId
          expires
          nftAddress
          ticketsSold
          ticketBatches
          winningTicket
          closeTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          chainId
          winningAccount
          owner
          contract
          nft {
            id
            type
            createdAt
            updatedAt
            contractAddress
            metadata
            tokenUri
            tokenId
            symbol
            imageUri
            tokenName
            collectionName
            lastSales
            chainId
            rarityData
            nFTCollectionId
            __typename
          }
          refundTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          raffleWinningBatchId
          raffleReleaseTxId
          raffleOpenTxId
          raffleDrawnTxId
          raffleCloseTxId
          raffleNftId
          raffleRefundTxId
          __typename
        }
        ticketBatchTransactionId
        ticketBatchRaffleId
        __typename
      }
      releaseTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      progress
      openTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      drawnTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      state
      tokenId
      expires
      nftAddress
      ticketsSold
      ticketBatches
      winningTicket
      closeTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      chainId
      winningAccount
      owner
      contract
      nft {
        id
        type
        createdAt
        updatedAt
        contractAddress
        metadata
        tokenUri
        tokenId
        symbol
        imageUri
        tokenName
        collectionName
        lastSales
        chainId
        rarityData
        animationUrl
        collection {
          id
          type
          contractAddress
          createdAt
          updatedAt
          symbol
          rafflesCreated
          contractDeployer
          deployedBlockNumber
          tokenType
          totalSupply
          chainId
          name
          openseaSlug
          imageUrl
          externalUrl
          discordUrl
          twitterUsername
          description
          floorPrice
          __typename
        }
        nFTCollectionId
        __typename
      }
      refundTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      raffleWinningBatchId
      raffleReleaseTxId
      raffleOpenTxId
      raffleDrawnTxId
      raffleCloseTxId
      raffleNftId
      raffleRefundTxId
      __typename
    }
    tx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    ticketRefundRaffleId
    ticketRefundTxId
    __typename
  }
}
` as GeneratedMutation<
  APITypes.DeleteTicketRefundMutationVariables,
  APITypes.DeleteTicketRefundMutation
>;
export const createStat = /* GraphQL */ `mutation CreateStat(
  $input: CreateStatInput!
  $condition: ModelStatConditionInput
) {
  createStat(input: $input, condition: $condition) {
    id
    type
    createdAt
    updatedAt
    ethPaid
    ticketsBought
    royaltiesPaid
    chainId
    rafflesCreated
    __typename
  }
}
` as GeneratedMutation<
  APITypes.CreateStatMutationVariables,
  APITypes.CreateStatMutation
>;
export const updateStat = /* GraphQL */ `mutation UpdateStat(
  $input: UpdateStatInput!
  $condition: ModelStatConditionInput
) {
  updateStat(input: $input, condition: $condition) {
    id
    type
    createdAt
    updatedAt
    ethPaid
    ticketsBought
    royaltiesPaid
    chainId
    rafflesCreated
    __typename
  }
}
` as GeneratedMutation<
  APITypes.UpdateStatMutationVariables,
  APITypes.UpdateStatMutation
>;
export const deleteStat = /* GraphQL */ `mutation DeleteStat(
  $input: DeleteStatInput!
  $condition: ModelStatConditionInput
) {
  deleteStat(input: $input, condition: $condition) {
    id
    type
    createdAt
    updatedAt
    ethPaid
    ticketsBought
    royaltiesPaid
    chainId
    rafflesCreated
    __typename
  }
}
` as GeneratedMutation<
  APITypes.DeleteStatMutationVariables,
  APITypes.DeleteStatMutation
>;
export const createTicketBatch = /* GraphQL */ `mutation CreateTicketBatch(
  $input: CreateTicketBatchInput!
  $condition: ModelTicketBatchConditionInput
) {
  createTicketBatch(input: $input, condition: $condition) {
    id
    type
    createdAt
    updatedAt
    raffleNonce
    lastTicket
    transaction {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    purchaser
    ticketsBought
    batchId
    firstTicket
    chainId
    raffle {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      ticketsAvailable
      winningBatch {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        lastTicket
        transaction {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        purchaser
        ticketsBought
        batchId
        firstTicket
        chainId
        raffle {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          ticketsAvailable
          winningBatch {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            lastTicket
            purchaser
            ticketsBought
            batchId
            firstTicket
            chainId
            ticketBatchTransactionId
            ticketBatchRaffleId
            __typename
          }
          releaseTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          progress
          openTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          drawnTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          state
          tokenId
          expires
          nftAddress
          ticketsSold
          ticketBatches
          winningTicket
          closeTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          chainId
          winningAccount
          owner
          contract
          nft {
            id
            type
            createdAt
            updatedAt
            contractAddress
            metadata
            tokenUri
            tokenId
            symbol
            imageUri
            tokenName
            collectionName
            lastSales
            chainId
            rarityData
            nFTCollectionId
            __typename
          }
          refundTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          raffleWinningBatchId
          raffleReleaseTxId
          raffleOpenTxId
          raffleDrawnTxId
          raffleCloseTxId
          raffleNftId
          raffleRefundTxId
          __typename
        }
        ticketBatchTransactionId
        ticketBatchRaffleId
        __typename
      }
      releaseTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      progress
      openTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      drawnTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      state
      tokenId
      expires
      nftAddress
      ticketsSold
      ticketBatches
      winningTicket
      closeTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      chainId
      winningAccount
      owner
      contract
      nft {
        id
        type
        createdAt
        updatedAt
        contractAddress
        metadata
        tokenUri
        tokenId
        symbol
        imageUri
        tokenName
        collectionName
        lastSales
        chainId
        rarityData
        collection {
          id
          type
          contractAddress
          createdAt
          updatedAt
          symbol
          rafflesCreated
          contractDeployer
          deployedBlockNumber
          tokenType
          totalSupply
          chainId
          name
          openseaSlug
          imageUrl
          externalUrl
          discordUrl
          twitterUsername
          description
          floorPrice
          __typename
        }
        nFTCollectionId
        __typename
      }
      refundTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      raffleWinningBatchId
      raffleReleaseTxId
      raffleOpenTxId
      raffleDrawnTxId
      raffleCloseTxId
      raffleNftId
      raffleRefundTxId
      __typename
    }
    ticketBatchTransactionId
    ticketBatchRaffleId
    __typename
  }
}
` as GeneratedMutation<
  APITypes.CreateTicketBatchMutationVariables,
  APITypes.CreateTicketBatchMutation
>;
export const updateTicketBatch = /* GraphQL */ `mutation UpdateTicketBatch(
  $input: UpdateTicketBatchInput!
  $condition: ModelTicketBatchConditionInput
) {
  updateTicketBatch(input: $input, condition: $condition) {
    id
    type
    createdAt
    updatedAt
    raffleNonce
    lastTicket
    transaction {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    purchaser
    ticketsBought
    batchId
    firstTicket
    chainId
    raffle {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      ticketsAvailable
      winningBatch {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        lastTicket
        transaction {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        purchaser
        ticketsBought
        batchId
        firstTicket
        chainId
        raffle {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          ticketsAvailable
          winningBatch {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            lastTicket
            purchaser
            ticketsBought
            batchId
            firstTicket
            chainId
            ticketBatchTransactionId
            ticketBatchRaffleId
            __typename
          }
          releaseTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          progress
          openTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          drawnTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          state
          tokenId
          expires
          nftAddress
          ticketsSold
          ticketBatches
          winningTicket
          closeTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          chainId
          winningAccount
          owner
          contract
          nft {
            id
            type
            createdAt
            updatedAt
            contractAddress
            metadata
            tokenUri
            tokenId
            symbol
            imageUri
            tokenName
            collectionName
            lastSales
            chainId
            rarityData
            nFTCollectionId
            __typename
          }
          refundTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          raffleWinningBatchId
          raffleReleaseTxId
          raffleOpenTxId
          raffleDrawnTxId
          raffleCloseTxId
          raffleNftId
          raffleRefundTxId
          __typename
        }
        ticketBatchTransactionId
        ticketBatchRaffleId
        __typename
      }
      releaseTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      progress
      openTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      drawnTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      state
      tokenId
      expires
      nftAddress
      ticketsSold
      ticketBatches
      winningTicket
      closeTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      chainId
      winningAccount
      owner
      contract
      nft {
        id
        type
        createdAt
        updatedAt
        contractAddress
        metadata
        tokenUri
        tokenId
        symbol
        imageUri
        tokenName
        collectionName
        lastSales
        chainId
        rarityData
        collection {
          id
          type
          contractAddress
          createdAt
          updatedAt
          symbol
          rafflesCreated
          contractDeployer
          deployedBlockNumber
          tokenType
          totalSupply
          chainId
          name
          openseaSlug
          imageUrl
          externalUrl
          discordUrl
          twitterUsername
          description
          floorPrice
          __typename
        }
        nFTCollectionId
        __typename
      }
      refundTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      raffleWinningBatchId
      raffleReleaseTxId
      raffleOpenTxId
      raffleDrawnTxId
      raffleCloseTxId
      raffleNftId
      raffleRefundTxId
      __typename
    }
    ticketBatchTransactionId
    ticketBatchRaffleId
    __typename
  }
}
` as GeneratedMutation<
  APITypes.UpdateTicketBatchMutationVariables,
  APITypes.UpdateTicketBatchMutation
>;
export const deleteTicketBatch = /* GraphQL */ `mutation DeleteTicketBatch(
  $input: DeleteTicketBatchInput!
  $condition: ModelTicketBatchConditionInput
) {
  deleteTicketBatch(input: $input, condition: $condition) {
    id
    type
    createdAt
    updatedAt
    raffleNonce
    lastTicket
    transaction {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    purchaser
    ticketsBought
    batchId
    firstTicket
    chainId
    raffle {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      ticketsAvailable
      winningBatch {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        lastTicket
        transaction {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        purchaser
        ticketsBought
        batchId
        firstTicket
        chainId
        raffle {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          ticketsAvailable
          winningBatch {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            lastTicket
            purchaser
            ticketsBought
            batchId
            firstTicket
            chainId
            ticketBatchTransactionId
            ticketBatchRaffleId
            __typename
          }
          releaseTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          progress
          openTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          drawnTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          state
          tokenId
          expires
          nftAddress
          ticketsSold
          ticketBatches
          winningTicket
          closeTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          chainId
          winningAccount
          owner
          contract
          nft {
            id
            type
            createdAt
            updatedAt
            contractAddress
            metadata
            tokenUri
            tokenId
            symbol
            imageUri
            tokenName
            collectionName
            lastSales
            chainId
            rarityData
            nFTCollectionId
            __typename
          }
          refundTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          raffleWinningBatchId
          raffleReleaseTxId
          raffleOpenTxId
          raffleDrawnTxId
          raffleCloseTxId
          raffleNftId
          raffleRefundTxId
          __typename
        }
        ticketBatchTransactionId
        ticketBatchRaffleId
        __typename
      }
      releaseTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      progress
      openTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      drawnTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      state
      tokenId
      expires
      nftAddress
      ticketsSold
      ticketBatches
      winningTicket
      closeTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      chainId
      winningAccount
      owner
      contract
      nft {
        id
        type
        createdAt
        updatedAt
        contractAddress
        metadata
        tokenUri
        tokenId
        symbol
        imageUri
        tokenName
        collectionName
        lastSales
        chainId
        rarityData
        collection {
          id
          type
          contractAddress
          createdAt
          updatedAt
          symbol
          rafflesCreated
          contractDeployer
          deployedBlockNumber
          tokenType
          totalSupply
          chainId
          name
          openseaSlug
          imageUrl
          externalUrl
          discordUrl
          twitterUsername
          description
          floorPrice
          __typename
        }
        nFTCollectionId
        __typename
      }
      refundTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      raffleWinningBatchId
      raffleReleaseTxId
      raffleOpenTxId
      raffleDrawnTxId
      raffleCloseTxId
      raffleNftId
      raffleRefundTxId
      __typename
    }
    ticketBatchTransactionId
    ticketBatchRaffleId
    __typename
  }
}
` as GeneratedMutation<
  APITypes.DeleteTicketBatchMutationVariables,
  APITypes.DeleteTicketBatchMutation
>;
export const createTransaction = /* GraphQL */ `mutation CreateTransaction(
  $input: CreateTransactionInput!
  $condition: ModelTransactionConditionInput
) {
  createTransaction(input: $input, condition: $condition) {
    id
    type
    createdAt
    updatedAt
    raffleNonce
    date
    eventType
    hash
    chainId
    __typename
  }
}
` as GeneratedMutation<
  APITypes.CreateTransactionMutationVariables,
  APITypes.CreateTransactionMutation
>;
export const updateTransaction = /* GraphQL */ `mutation UpdateTransaction(
  $input: UpdateTransactionInput!
  $condition: ModelTransactionConditionInput
) {
  updateTransaction(input: $input, condition: $condition) {
    id
    type
    createdAt
    updatedAt
    raffleNonce
    date
    eventType
    hash
    chainId
    __typename
  }
}
` as GeneratedMutation<
  APITypes.UpdateTransactionMutationVariables,
  APITypes.UpdateTransactionMutation
>;
export const deleteTransaction = /* GraphQL */ `mutation DeleteTransaction(
  $input: DeleteTransactionInput!
  $condition: ModelTransactionConditionInput
) {
  deleteTransaction(input: $input, condition: $condition) {
    id
    type
    createdAt
    updatedAt
    raffleNonce
    date
    eventType
    hash
    chainId
    __typename
  }
}
` as GeneratedMutation<
  APITypes.DeleteTransactionMutationVariables,
  APITypes.DeleteTransactionMutation
>;
export const createRaffle = /* GraphQL */ `mutation CreateRaffle(
  $input: CreateRaffleInput!
  $condition: ModelRaffleConditionInput
) {
  createRaffle(input: $input, condition: $condition) {
    id
    type
    createdAt
    updatedAt
    raffleNonce
    ticketsAvailable
    winningBatch {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      lastTicket
      transaction {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      purchaser
      ticketsBought
      batchId
      firstTicket
      chainId
      raffle {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        ticketsAvailable
        winningBatch {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          lastTicket
          transaction {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          purchaser
          ticketsBought
          batchId
          firstTicket
          chainId
          raffle {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            ticketsAvailable
            progress
            state
            tokenId
            expires
            nftAddress
            ticketsSold
            ticketBatches
            winningTicket
            chainId
            winningAccount
            owner
            contract
            raffleWinningBatchId
            raffleReleaseTxId
            raffleOpenTxId
            raffleDrawnTxId
            raffleCloseTxId
            raffleNftId
            raffleRefundTxId
            __typename
          }
          ticketBatchTransactionId
          ticketBatchRaffleId
          __typename
        }
        releaseTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        progress
        openTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        drawnTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        state
        tokenId
        expires
        nftAddress
        ticketsSold
        ticketBatches
        winningTicket
        closeTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        chainId
        winningAccount
        owner
        contract
        nft {
          id
          type
          createdAt
          updatedAt
          contractAddress
          metadata
          tokenUri
          tokenId
          symbol
          imageUri
          tokenName
          collectionName
          lastSales
          chainId
          rarityData
          collection {
            id
            type
            contractAddress
            createdAt
            updatedAt
            symbol
            rafflesCreated
            contractDeployer
            deployedBlockNumber
            tokenType
            totalSupply
            chainId
            name
            openseaSlug
            imageUrl
            externalUrl
            discordUrl
            twitterUsername
            description
            floorPrice
            __typename
          }
          nFTCollectionId
          __typename
        }
        refundTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        raffleWinningBatchId
        raffleReleaseTxId
        raffleOpenTxId
        raffleDrawnTxId
        raffleCloseTxId
        raffleNftId
        raffleRefundTxId
        __typename
      }
      ticketBatchTransactionId
      ticketBatchRaffleId
      __typename
    }
    releaseTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    progress
    openTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    drawnTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    state
    tokenId
    expires
    nftAddress
    ticketsSold
    ticketBatches
    winningTicket
    closeTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    chainId
    winningAccount
    owner
    contract
    nft {
      id
      type
      createdAt
      updatedAt
      contractAddress
      metadata
      tokenUri
      tokenId
      symbol
      imageUri
      tokenName
      collectionName
      lastSales
      chainId
      rarityData
      animationUrl
      collection {
        id
        type
        contractAddress
        createdAt
        updatedAt
        symbol
        rafflesCreated
        contractDeployer
        deployedBlockNumber
        tokenType
        totalSupply
        chainId
        name
        openseaSlug
        imageUrl
        externalUrl
        discordUrl
        twitterUsername
        description
        floorPrice
        __typename
      }
      nFTCollectionId
      __typename
    }
    refundTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    raffleWinningBatchId
    raffleReleaseTxId
    raffleOpenTxId
    raffleDrawnTxId
    raffleCloseTxId
    raffleNftId
    raffleRefundTxId
    __typename
  }
}
` as GeneratedMutation<
  APITypes.CreateRaffleMutationVariables,
  APITypes.CreateRaffleMutation
>;
export const updateRaffle = /* GraphQL */ `mutation UpdateRaffle(
  $input: UpdateRaffleInput!
  $condition: ModelRaffleConditionInput
) {
  updateRaffle(input: $input, condition: $condition) {
    id
    type
    createdAt
    updatedAt
    raffleNonce
    ticketsAvailable
    winningBatch {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      lastTicket
      transaction {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      purchaser
      ticketsBought
      batchId
      firstTicket
      chainId
      raffle {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        ticketsAvailable
        winningBatch {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          lastTicket
          transaction {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          purchaser
          ticketsBought
          batchId
          firstTicket
          chainId
          raffle {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            ticketsAvailable
            progress
            state
            tokenId
            expires
            nftAddress
            ticketsSold
            ticketBatches
            winningTicket
            chainId
            winningAccount
            owner
            contract
            raffleWinningBatchId
            raffleReleaseTxId
            raffleOpenTxId
            raffleDrawnTxId
            raffleCloseTxId
            raffleNftId
            raffleRefundTxId
            __typename
          }
          ticketBatchTransactionId
          ticketBatchRaffleId
          __typename
        }
        releaseTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        progress
        openTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        drawnTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        state
        tokenId
        expires
        nftAddress
        ticketsSold
        ticketBatches
        winningTicket
        closeTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        chainId
        winningAccount
        owner
        contract
        nft {
          id
          type
          createdAt
          updatedAt
          contractAddress
          metadata
          tokenUri
          tokenId
          symbol
          imageUri
          tokenName
          collectionName
          lastSales
          chainId
          rarityData
          collection {
            id
            type
            contractAddress
            createdAt
            updatedAt
            symbol
            rafflesCreated
            contractDeployer
            deployedBlockNumber
            tokenType
            totalSupply
            chainId
            name
            openseaSlug
            imageUrl
            externalUrl
            discordUrl
            twitterUsername
            description
            floorPrice
            __typename
          }
          nFTCollectionId
          __typename
        }
        refundTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        raffleWinningBatchId
        raffleReleaseTxId
        raffleOpenTxId
        raffleDrawnTxId
        raffleCloseTxId
        raffleNftId
        raffleRefundTxId
        __typename
      }
      ticketBatchTransactionId
      ticketBatchRaffleId
      __typename
    }
    releaseTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    progress
    openTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    drawnTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    state
    tokenId
    expires
    nftAddress
    ticketsSold
    ticketBatches
    winningTicket
    closeTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    chainId
    winningAccount
    owner
    contract
    nft {
      id
      type
      createdAt
      updatedAt
      contractAddress
      metadata
      tokenUri
      tokenId
      symbol
      imageUri
      tokenName
      collectionName
      lastSales
      chainId
      rarityData
      animationUrl
      collection {
        id
        type
        contractAddress
        createdAt
        updatedAt
        symbol
        rafflesCreated
        contractDeployer
        deployedBlockNumber
        tokenType
        totalSupply
        chainId
        name
        openseaSlug
        imageUrl
        externalUrl
        discordUrl
        twitterUsername
        description
        floorPrice
        __typename
      }
      nFTCollectionId
      __typename
    }
    refundTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    raffleWinningBatchId
    raffleReleaseTxId
    raffleOpenTxId
    raffleDrawnTxId
    raffleCloseTxId
    raffleNftId
    raffleRefundTxId
    __typename
  }
}
` as GeneratedMutation<
  APITypes.UpdateRaffleMutationVariables,
  APITypes.UpdateRaffleMutation
>;
export const deleteRaffle = /* GraphQL */ `mutation DeleteRaffle(
  $input: DeleteRaffleInput!
  $condition: ModelRaffleConditionInput
) {
  deleteRaffle(input: $input, condition: $condition) {
    id
    type
    createdAt
    updatedAt
    raffleNonce
    ticketsAvailable
    winningBatch {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      lastTicket
      transaction {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      purchaser
      ticketsBought
      batchId
      firstTicket
      chainId
      raffle {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        ticketsAvailable
        winningBatch {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          lastTicket
          transaction {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          purchaser
          ticketsBought
          batchId
          firstTicket
          chainId
          raffle {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            ticketsAvailable
            progress
            state
            tokenId
            expires
            nftAddress
            ticketsSold
            ticketBatches
            winningTicket
            chainId
            winningAccount
            owner
            contract
            raffleWinningBatchId
            raffleReleaseTxId
            raffleOpenTxId
            raffleDrawnTxId
            raffleCloseTxId
            raffleNftId
            raffleRefundTxId
            __typename
          }
          ticketBatchTransactionId
          ticketBatchRaffleId
          __typename
        }
        releaseTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        progress
        openTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        drawnTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        state
        tokenId
        expires
        nftAddress
        ticketsSold
        ticketBatches
        winningTicket
        closeTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        chainId
        winningAccount
        owner
        contract
        nft {
          id
          type
          createdAt
          updatedAt
          contractAddress
          metadata
          tokenUri
          tokenId
          symbol
          imageUri
          tokenName
          collectionName
          lastSales
          chainId
          rarityData
          collection {
            id
            type
            contractAddress
            createdAt
            updatedAt
            symbol
            rafflesCreated
            contractDeployer
            deployedBlockNumber
            tokenType
            totalSupply
            chainId
            name
            openseaSlug
            imageUrl
            externalUrl
            discordUrl
            twitterUsername
            description
            floorPrice
            __typename
          }
          nFTCollectionId
          __typename
        }
        refundTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        raffleWinningBatchId
        raffleReleaseTxId
        raffleOpenTxId
        raffleDrawnTxId
        raffleCloseTxId
        raffleNftId
        raffleRefundTxId
        __typename
      }
      ticketBatchTransactionId
      ticketBatchRaffleId
      __typename
    }
    releaseTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    progress
    openTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    drawnTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    state
    tokenId
    expires
    nftAddress
    ticketsSold
    ticketBatches
    winningTicket
    closeTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    chainId
    winningAccount
    owner
    contract
    nft {
      id
      type
      createdAt
      updatedAt
      contractAddress
      metadata
      tokenUri
      tokenId
      symbol
      imageUri
      tokenName
      collectionName
      lastSales
      chainId
      rarityData
      animationUrl
      collection {
        id
        type
        contractAddress
        createdAt
        updatedAt
        symbol
        rafflesCreated
        contractDeployer
        deployedBlockNumber
        tokenType
        totalSupply
        chainId
        name
        openseaSlug
        imageUrl
        externalUrl
        discordUrl
        twitterUsername
        description
        floorPrice
        __typename
      }
      nFTCollectionId
      __typename
    }
    refundTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    raffleWinningBatchId
    raffleReleaseTxId
    raffleOpenTxId
    raffleDrawnTxId
    raffleCloseTxId
    raffleNftId
    raffleRefundTxId
    __typename
  }
}
` as GeneratedMutation<
  APITypes.DeleteRaffleMutationVariables,
  APITypes.DeleteRaffleMutation
>;
export const createNFT = /* GraphQL */ `mutation CreateNFT(
  $input: CreateNFTInput!
  $condition: ModelNFTConditionInput
) {
  createNFT(input: $input, condition: $condition) {
    id
    type
    createdAt
    updatedAt
    contractAddress
    metadata
    tokenUri
    tokenId
    symbol
    imageUri
    tokenName
    collectionName
    lastSales
    chainId
    rarityData
    collection {
      id
      type
      contractAddress
      createdAt
      updatedAt
      symbol
      rafflesCreated
      contractDeployer
      deployedBlockNumber
      tokenType
      totalSupply
      chainId
      name
      openseaSlug
      imageUrl
      externalUrl
      discordUrl
      twitterUsername
      description
      floorPrice
      __typename
    }
    nFTCollectionId
    __typename
  }
}
` as GeneratedMutation<
  APITypes.CreateNFTMutationVariables,
  APITypes.CreateNFTMutation
>;
export const updateNFT = /* GraphQL */ `mutation UpdateNFT(
  $input: UpdateNFTInput!
  $condition: ModelNFTConditionInput
) {
  updateNFT(input: $input, condition: $condition) {
    id
    type
    createdAt
    updatedAt
    contractAddress
    metadata
    tokenUri
    tokenId
    symbol
    imageUri
    tokenName
    collectionName
    lastSales
    chainId
    rarityData
    collection {
      id
      type
      contractAddress
      createdAt
      updatedAt
      symbol
      rafflesCreated
      contractDeployer
      deployedBlockNumber
      tokenType
      totalSupply
      chainId
      name
      openseaSlug
      imageUrl
      externalUrl
      discordUrl
      twitterUsername
      description
      floorPrice
      __typename
    }
    nFTCollectionId
    __typename
  }
}
` as GeneratedMutation<
  APITypes.UpdateNFTMutationVariables,
  APITypes.UpdateNFTMutation
>;
export const deleteNFT = /* GraphQL */ `mutation DeleteNFT(
  $input: DeleteNFTInput!
  $condition: ModelNFTConditionInput
) {
  deleteNFT(input: $input, condition: $condition) {
    id
    type
    createdAt
    updatedAt
    contractAddress
    metadata
    tokenUri
    tokenId
    symbol
    imageUri
    tokenName
    collectionName
    lastSales
    chainId
    rarityData
    collection {
      id
      type
      contractAddress
      createdAt
      updatedAt
      symbol
      rafflesCreated
      contractDeployer
      deployedBlockNumber
      tokenType
      totalSupply
      chainId
      name
      openseaSlug
      imageUrl
      externalUrl
      discordUrl
      twitterUsername
      description
      floorPrice
      __typename
    }
    nFTCollectionId
    __typename
  }
}
` as GeneratedMutation<
  APITypes.DeleteNFTMutationVariables,
  APITypes.DeleteNFTMutation
>;
export const createCollection = /* GraphQL */ `mutation CreateCollection(
  $input: CreateCollectionInput!
  $condition: ModelCollectionConditionInput
) {
  createCollection(input: $input, condition: $condition) {
    id
    type
    contractAddress
    createdAt
    updatedAt
    symbol
    rafflesCreated
    contractDeployer
    deployedBlockNumber
    tokenType
    totalSupply
    chainId
    name
    openseaSlug
    imageUrl
    externalUrl
    discordUrl
    twitterUsername
    description
    floorPrice
    __typename
  }
}
` as GeneratedMutation<
  APITypes.CreateCollectionMutationVariables,
  APITypes.CreateCollectionMutation
>;
export const updateCollection = /* GraphQL */ `mutation UpdateCollection(
  $input: UpdateCollectionInput!
  $condition: ModelCollectionConditionInput
) {
  updateCollection(input: $input, condition: $condition) {
    id
    type
    contractAddress
    createdAt
    updatedAt
    symbol
    rafflesCreated
    contractDeployer
    deployedBlockNumber
    tokenType
    totalSupply
    chainId
    name
    openseaSlug
    imageUrl
    externalUrl
    discordUrl
    twitterUsername
    description
    floorPrice
    __typename
  }
}
` as GeneratedMutation<
  APITypes.UpdateCollectionMutationVariables,
  APITypes.UpdateCollectionMutation
>;
export const deleteCollection = /* GraphQL */ `mutation DeleteCollection(
  $input: DeleteCollectionInput!
  $condition: ModelCollectionConditionInput
) {
  deleteCollection(input: $input, condition: $condition) {
    id
    type
    contractAddress
    createdAt
    updatedAt
    symbol
    rafflesCreated
    contractDeployer
    deployedBlockNumber
    tokenType
    totalSupply
    chainId
    name
    openseaSlug
    imageUrl
    externalUrl
    discordUrl
    twitterUsername
    description
    floorPrice
    __typename
  }
}
` as GeneratedMutation<
  APITypes.DeleteCollectionMutationVariables,
  APITypes.DeleteCollectionMutation
>;
export const createAccount = /* GraphQL */ `mutation CreateAccount(
  $input: CreateAccountInput!
  $condition: ModelAccountConditionInput
) {
  createAccount(input: $input, condition: $condition) {
    id
    type
    createdAt
    updatedAt
    address
    rafflesCreated
    rafflesWon
    rafflesEntered
    ticketsBought
    __typename
  }
}
` as GeneratedMutation<
  APITypes.CreateAccountMutationVariables,
  APITypes.CreateAccountMutation
>;
export const updateAccount = /* GraphQL */ `mutation UpdateAccount(
  $input: UpdateAccountInput!
  $condition: ModelAccountConditionInput
) {
  updateAccount(input: $input, condition: $condition) {
    id
    type
    createdAt
    updatedAt
    address
    rafflesCreated
    rafflesWon
    rafflesEntered
    ticketsBought
    __typename
  }
}
` as GeneratedMutation<
  APITypes.UpdateAccountMutationVariables,
  APITypes.UpdateAccountMutation
>;
export const deleteAccount = /* GraphQL */ `mutation DeleteAccount(
  $input: DeleteAccountInput!
  $condition: ModelAccountConditionInput
) {
  deleteAccount(input: $input, condition: $condition) {
    id
    type
    createdAt
    updatedAt
    address
    rafflesCreated
    rafflesWon
    rafflesEntered
    ticketsBought
    __typename
  }
}
` as GeneratedMutation<
  APITypes.DeleteAccountMutationVariables,
  APITypes.DeleteAccountMutation
>;
