/* tslint:disable */
/* eslint-disable */
// this is an auto generated file. This will be overwritten

import * as APITypes from "../API";
type GeneratedSubscription<InputType, OutputType> = string & {
  __generatedSubscriptionInput: InputType;
  __generatedSubscriptionOutput: OutputType;
};

export const onCreateTicketRefund = /* GraphQL */ `subscription OnCreateTicketRefund(
  $filter: ModelSubscriptionTicketRefundFilterInput
) {
  onCreateTicketRefund(filter: $filter) {
    id
    type
    createdAt
    updatedAt
    raffleNonce
    ethAmount
    refundee
    chainId
    raffle {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      ticketsAvailable
      winningBatch {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        lastTicket
        transaction {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        purchaser
        ticketsBought
        batchId
        firstTicket
        chainId
        raffle {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          ticketsAvailable
          winningBatch {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            lastTicket
            purchaser
            ticketsBought
            batchId
            firstTicket
            chainId
            ticketBatchTransactionId
            ticketBatchRaffleId
            __typename
          }
          releaseTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          progress
          openTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          drawnTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          state
          tokenId
          expires
          nftAddress
          ticketsSold
          ticketBatches
          winningTicket
          closeTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          chainId
          winningAccount
          owner
          contract
          nft {
            id
            type
            createdAt
            updatedAt
            contractAddress
            metadata
            tokenUri
            tokenId
            symbol
            imageUri
            tokenName
            collectionName
            lastSales
            chainId
            rarityData
            nFTCollectionId
            __typename
          }
          refundTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          raffleWinningBatchId
          raffleReleaseTxId
          raffleOpenTxId
          raffleDrawnTxId
          raffleCloseTxId
          raffleNftId
          raffleRefundTxId
          __typename
        }
        ticketBatchTransactionId
        ticketBatchRaffleId
        __typename
      }
      releaseTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      progress
      openTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      drawnTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      state
      tokenId
      expires
      nftAddress
      ticketsSold
      ticketBatches
      winningTicket
      closeTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      chainId
      winningAccount
      owner
      contract
      nft {
        id
        type
        createdAt
        updatedAt
        contractAddress
        metadata
        tokenUri
        tokenId
        symbol
        imageUri
        tokenName
        collectionName
        lastSales
        chainId
        rarityData
        collection {
          id
          type
          contractAddress
          createdAt
          updatedAt
          symbol
          rafflesCreated
          contractDeployer
          deployedBlockNumber
          tokenType
          totalSupply
          chainId
          name
          openseaSlug
          imageUrl
          externalUrl
          discordUrl
          twitterUsername
          description
          floorPrice
          __typename
        }
        nFTCollectionId
        __typename
      }
      refundTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      raffleWinningBatchId
      raffleReleaseTxId
      raffleOpenTxId
      raffleDrawnTxId
      raffleCloseTxId
      raffleNftId
      raffleRefundTxId
      __typename
    }
    tx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    ticketRefundRaffleId
    ticketRefundTxId
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnCreateTicketRefundSubscriptionVariables,
  APITypes.OnCreateTicketRefundSubscription
>;
export const onUpdateTicketRefund = /* GraphQL */ `subscription OnUpdateTicketRefund(
  $filter: ModelSubscriptionTicketRefundFilterInput
) {
  onUpdateTicketRefund(filter: $filter) {
    id
    type
    createdAt
    updatedAt
    raffleNonce
    ethAmount
    refundee
    chainId
    raffle {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      ticketsAvailable
      winningBatch {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        lastTicket
        transaction {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        purchaser
        ticketsBought
        batchId
        firstTicket
        chainId
        raffle {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          ticketsAvailable
          winningBatch {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            lastTicket
            purchaser
            ticketsBought
            batchId
            firstTicket
            chainId
            ticketBatchTransactionId
            ticketBatchRaffleId
            __typename
          }
          releaseTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          progress
          openTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          drawnTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          state
          tokenId
          expires
          nftAddress
          ticketsSold
          ticketBatches
          winningTicket
          closeTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          chainId
          winningAccount
          owner
          contract
          nft {
            id
            type
            createdAt
            updatedAt
            contractAddress
            metadata
            tokenUri
            tokenId
            symbol
            imageUri
            tokenName
            collectionName
            lastSales
            chainId
            rarityData
            nFTCollectionId
            __typename
          }
          refundTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          raffleWinningBatchId
          raffleReleaseTxId
          raffleOpenTxId
          raffleDrawnTxId
          raffleCloseTxId
          raffleNftId
          raffleRefundTxId
          __typename
        }
        ticketBatchTransactionId
        ticketBatchRaffleId
        __typename
      }
      releaseTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      progress
      openTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      drawnTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      state
      tokenId
      expires
      nftAddress
      ticketsSold
      ticketBatches
      winningTicket
      closeTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      chainId
      winningAccount
      owner
      contract
      nft {
        id
        type
        createdAt
        updatedAt
        contractAddress
        metadata
        tokenUri
        tokenId
        symbol
        imageUri
        tokenName
        collectionName
        lastSales
        chainId
        rarityData
        collection {
          id
          type
          contractAddress
          createdAt
          updatedAt
          symbol
          rafflesCreated
          contractDeployer
          deployedBlockNumber
          tokenType
          totalSupply
          chainId
          name
          openseaSlug
          imageUrl
          externalUrl
          discordUrl
          twitterUsername
          description
          floorPrice
          __typename
        }
        nFTCollectionId
        __typename
      }
      refundTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      raffleWinningBatchId
      raffleReleaseTxId
      raffleOpenTxId
      raffleDrawnTxId
      raffleCloseTxId
      raffleNftId
      raffleRefundTxId
      __typename
    }
    tx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    ticketRefundRaffleId
    ticketRefundTxId
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnUpdateTicketRefundSubscriptionVariables,
  APITypes.OnUpdateTicketRefundSubscription
>;
export const onDeleteTicketRefund = /* GraphQL */ `subscription OnDeleteTicketRefund(
  $filter: ModelSubscriptionTicketRefundFilterInput
) {
  onDeleteTicketRefund(filter: $filter) {
    id
    type
    createdAt
    updatedAt
    raffleNonce
    ethAmount
    refundee
    chainId
    raffle {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      ticketsAvailable
      winningBatch {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        lastTicket
        transaction {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        purchaser
        ticketsBought
        batchId
        firstTicket
        chainId
        raffle {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          ticketsAvailable
          winningBatch {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            lastTicket
            purchaser
            ticketsBought
            batchId
            firstTicket
            chainId
            ticketBatchTransactionId
            ticketBatchRaffleId
            __typename
          }
          releaseTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          progress
          openTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          drawnTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          state
          tokenId
          expires
          nftAddress
          ticketsSold
          ticketBatches
          winningTicket
          closeTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          chainId
          winningAccount
          owner
          contract
          nft {
            id
            type
            createdAt
            updatedAt
            contractAddress
            metadata
            tokenUri
            tokenId
            symbol
            imageUri
            tokenName
            collectionName
            lastSales
            chainId
            rarityData
            nFTCollectionId
            __typename
          }
          refundTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          raffleWinningBatchId
          raffleReleaseTxId
          raffleOpenTxId
          raffleDrawnTxId
          raffleCloseTxId
          raffleNftId
          raffleRefundTxId
          __typename
        }
        ticketBatchTransactionId
        ticketBatchRaffleId
        __typename
      }
      releaseTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      progress
      openTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      drawnTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      state
      tokenId
      expires
      nftAddress
      ticketsSold
      ticketBatches
      winningTicket
      closeTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      chainId
      winningAccount
      owner
      contract
      nft {
        id
        type
        createdAt
        updatedAt
        contractAddress
        metadata
        tokenUri
        tokenId
        symbol
        imageUri
        tokenName
        collectionName
        lastSales
        chainId
        rarityData
        collection {
          id
          type
          contractAddress
          createdAt
          updatedAt
          symbol
          rafflesCreated
          contractDeployer
          deployedBlockNumber
          tokenType
          totalSupply
          chainId
          name
          openseaSlug
          imageUrl
          externalUrl
          discordUrl
          twitterUsername
          description
          floorPrice
          __typename
        }
        nFTCollectionId
        __typename
      }
      refundTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      raffleWinningBatchId
      raffleReleaseTxId
      raffleOpenTxId
      raffleDrawnTxId
      raffleCloseTxId
      raffleNftId
      raffleRefundTxId
      __typename
    }
    tx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    ticketRefundRaffleId
    ticketRefundTxId
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnDeleteTicketRefundSubscriptionVariables,
  APITypes.OnDeleteTicketRefundSubscription
>;
export const onCreateStat = /* GraphQL */ `subscription OnCreateStat($filter: ModelSubscriptionStatFilterInput) {
  onCreateStat(filter: $filter) {
    id
    type
    createdAt
    updatedAt
    ethPaid
    ticketsBought
    royaltiesPaid
    chainId
    rafflesCreated
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnCreateStatSubscriptionVariables,
  APITypes.OnCreateStatSubscription
>;
export const onUpdateStat = /* GraphQL */ `subscription OnUpdateStat($filter: ModelSubscriptionStatFilterInput) {
  onUpdateStat(filter: $filter) {
    id
    type
    createdAt
    updatedAt
    ethPaid
    ticketsBought
    royaltiesPaid
    chainId
    rafflesCreated
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnUpdateStatSubscriptionVariables,
  APITypes.OnUpdateStatSubscription
>;
export const onDeleteStat = /* GraphQL */ `subscription OnDeleteStat($filter: ModelSubscriptionStatFilterInput) {
  onDeleteStat(filter: $filter) {
    id
    type
    createdAt
    updatedAt
    ethPaid
    ticketsBought
    royaltiesPaid
    chainId
    rafflesCreated
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnDeleteStatSubscriptionVariables,
  APITypes.OnDeleteStatSubscription
>;
export const onCreateTicketBatch = /* GraphQL */ `subscription OnCreateTicketBatch(
  $filter: ModelSubscriptionTicketBatchFilterInput
) {
  onCreateTicketBatch(filter: $filter) {
    id
    type
    createdAt
    updatedAt
    raffleNonce
    lastTicket
    transaction {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    purchaser
    ticketsBought
    batchId
    firstTicket
    chainId
    raffle {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      ticketsAvailable
      winningBatch {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        lastTicket
        transaction {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        purchaser
        ticketsBought
        batchId
        firstTicket
        chainId
        raffle {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          ticketsAvailable
          winningBatch {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            lastTicket
            purchaser
            ticketsBought
            batchId
            firstTicket
            chainId
            ticketBatchTransactionId
            ticketBatchRaffleId
            __typename
          }
          releaseTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          progress
          openTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          drawnTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          state
          tokenId
          expires
          nftAddress
          ticketsSold
          ticketBatches
          winningTicket
          closeTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          chainId
          winningAccount
          owner
          contract
          nft {
            id
            type
            createdAt
            updatedAt
            contractAddress
            metadata
            tokenUri
            tokenId
            symbol
            imageUri
            tokenName
            collectionName
            lastSales
            chainId
            rarityData
            nFTCollectionId
            __typename
          }
          refundTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          raffleWinningBatchId
          raffleReleaseTxId
          raffleOpenTxId
          raffleDrawnTxId
          raffleCloseTxId
          raffleNftId
          raffleRefundTxId
          __typename
        }
        ticketBatchTransactionId
        ticketBatchRaffleId
        __typename
      }
      releaseTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      progress
      openTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      drawnTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      state
      tokenId
      expires
      nftAddress
      ticketsSold
      ticketBatches
      winningTicket
      closeTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      chainId
      winningAccount
      owner
      contract
      nft {
        id
        type
        createdAt
        updatedAt
        contractAddress
        metadata
        tokenUri
        tokenId
        symbol
        imageUri
        tokenName
        collectionName
        lastSales
        chainId
        rarityData
        collection {
          id
          type
          contractAddress
          createdAt
          updatedAt
          symbol
          rafflesCreated
          contractDeployer
          deployedBlockNumber
          tokenType
          totalSupply
          chainId
          name
          openseaSlug
          imageUrl
          externalUrl
          discordUrl
          twitterUsername
          description
          floorPrice
          __typename
        }
        nFTCollectionId
        __typename
      }
      refundTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      raffleWinningBatchId
      raffleReleaseTxId
      raffleOpenTxId
      raffleDrawnTxId
      raffleCloseTxId
      raffleNftId
      raffleRefundTxId
      __typename
    }
    ticketBatchTransactionId
    ticketBatchRaffleId
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnCreateTicketBatchSubscriptionVariables,
  APITypes.OnCreateTicketBatchSubscription
>;
export const onUpdateTicketBatch = /* GraphQL */ `subscription OnUpdateTicketBatch(
  $filter: ModelSubscriptionTicketBatchFilterInput
) {
  onUpdateTicketBatch(filter: $filter) {
    id
    type
    createdAt
    updatedAt
    raffleNonce
    lastTicket
    transaction {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    purchaser
    ticketsBought
    batchId
    firstTicket
    chainId
    raffle {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      ticketsAvailable
      winningBatch {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        lastTicket
        transaction {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        purchaser
        ticketsBought
        batchId
        firstTicket
        chainId
        raffle {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          ticketsAvailable
          winningBatch {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            lastTicket
            purchaser
            ticketsBought
            batchId
            firstTicket
            chainId
            ticketBatchTransactionId
            ticketBatchRaffleId
            __typename
          }
          releaseTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          progress
          openTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          drawnTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          state
          tokenId
          expires
          nftAddress
          ticketsSold
          ticketBatches
          winningTicket
          closeTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          chainId
          winningAccount
          owner
          contract
          nft {
            id
            type
            createdAt
            updatedAt
            contractAddress
            metadata
            tokenUri
            tokenId
            symbol
            imageUri
            tokenName
            collectionName
            lastSales
            chainId
            rarityData
            nFTCollectionId
            __typename
          }
          refundTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          raffleWinningBatchId
          raffleReleaseTxId
          raffleOpenTxId
          raffleDrawnTxId
          raffleCloseTxId
          raffleNftId
          raffleRefundTxId
          __typename
        }
        ticketBatchTransactionId
        ticketBatchRaffleId
        __typename
      }
      releaseTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      progress
      openTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      drawnTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      state
      tokenId
      expires
      nftAddress
      ticketsSold
      ticketBatches
      winningTicket
      closeTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      chainId
      winningAccount
      owner
      contract
      nft {
        id
        type
        createdAt
        updatedAt
        contractAddress
        metadata
        tokenUri
        tokenId
        symbol
        imageUri
        tokenName
        collectionName
        lastSales
        chainId
        rarityData
        collection {
          id
          type
          contractAddress
          createdAt
          updatedAt
          symbol
          rafflesCreated
          contractDeployer
          deployedBlockNumber
          tokenType
          totalSupply
          chainId
          name
          openseaSlug
          imageUrl
          externalUrl
          discordUrl
          twitterUsername
          description
          floorPrice
          __typename
        }
        nFTCollectionId
        __typename
      }
      refundTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      raffleWinningBatchId
      raffleReleaseTxId
      raffleOpenTxId
      raffleDrawnTxId
      raffleCloseTxId
      raffleNftId
      raffleRefundTxId
      __typename
    }
    ticketBatchTransactionId
    ticketBatchRaffleId
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnUpdateTicketBatchSubscriptionVariables,
  APITypes.OnUpdateTicketBatchSubscription
>;
export const onDeleteTicketBatch = /* GraphQL */ `subscription OnDeleteTicketBatch(
  $filter: ModelSubscriptionTicketBatchFilterInput
) {
  onDeleteTicketBatch(filter: $filter) {
    id
    type
    createdAt
    updatedAt
    raffleNonce
    lastTicket
    transaction {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    purchaser
    ticketsBought
    batchId
    firstTicket
    chainId
    raffle {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      ticketsAvailable
      winningBatch {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        lastTicket
        transaction {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        purchaser
        ticketsBought
        batchId
        firstTicket
        chainId
        raffle {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          ticketsAvailable
          winningBatch {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            lastTicket
            purchaser
            ticketsBought
            batchId
            firstTicket
            chainId
            ticketBatchTransactionId
            ticketBatchRaffleId
            __typename
          }
          releaseTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          progress
          openTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          drawnTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          state
          tokenId
          expires
          nftAddress
          ticketsSold
          ticketBatches
          winningTicket
          closeTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          chainId
          winningAccount
          owner
          contract
          nft {
            id
            type
            createdAt
            updatedAt
            contractAddress
            metadata
            tokenUri
            tokenId
            symbol
            imageUri
            tokenName
            collectionName
            lastSales
            chainId
            rarityData
            nFTCollectionId
            __typename
          }
          refundTx {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          raffleWinningBatchId
          raffleReleaseTxId
          raffleOpenTxId
          raffleDrawnTxId
          raffleCloseTxId
          raffleNftId
          raffleRefundTxId
          __typename
        }
        ticketBatchTransactionId
        ticketBatchRaffleId
        __typename
      }
      releaseTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      progress
      openTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      drawnTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      state
      tokenId
      expires
      nftAddress
      ticketsSold
      ticketBatches
      winningTicket
      closeTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      chainId
      winningAccount
      owner
      contract
      nft {
        id
        type
        createdAt
        updatedAt
        contractAddress
        metadata
        tokenUri
        tokenId
        symbol
        imageUri
        tokenName
        collectionName
        lastSales
        chainId
        rarityData
        collection {
          id
          type
          contractAddress
          createdAt
          updatedAt
          symbol
          rafflesCreated
          contractDeployer
          deployedBlockNumber
          tokenType
          totalSupply
          chainId
          name
          openseaSlug
          imageUrl
          externalUrl
          discordUrl
          twitterUsername
          description
          floorPrice
          __typename
        }
        nFTCollectionId
        __typename
      }
      refundTx {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      raffleWinningBatchId
      raffleReleaseTxId
      raffleOpenTxId
      raffleDrawnTxId
      raffleCloseTxId
      raffleNftId
      raffleRefundTxId
      __typename
    }
    ticketBatchTransactionId
    ticketBatchRaffleId
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnDeleteTicketBatchSubscriptionVariables,
  APITypes.OnDeleteTicketBatchSubscription
>;
export const onCreateTransaction = /* GraphQL */ `subscription OnCreateTransaction(
  $filter: ModelSubscriptionTransactionFilterInput
) {
  onCreateTransaction(filter: $filter) {
    id
    type
    createdAt
    updatedAt
    raffleNonce
    date
    eventType
    hash
    chainId
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnCreateTransactionSubscriptionVariables,
  APITypes.OnCreateTransactionSubscription
>;
export const onUpdateTransaction = /* GraphQL */ `subscription OnUpdateTransaction(
  $filter: ModelSubscriptionTransactionFilterInput
) {
  onUpdateTransaction(filter: $filter) {
    id
    type
    createdAt
    updatedAt
    raffleNonce
    date
    eventType
    hash
    chainId
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnUpdateTransactionSubscriptionVariables,
  APITypes.OnUpdateTransactionSubscription
>;
export const onDeleteTransaction = /* GraphQL */ `subscription OnDeleteTransaction(
  $filter: ModelSubscriptionTransactionFilterInput
) {
  onDeleteTransaction(filter: $filter) {
    id
    type
    createdAt
    updatedAt
    raffleNonce
    date
    eventType
    hash
    chainId
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnDeleteTransactionSubscriptionVariables,
  APITypes.OnDeleteTransactionSubscription
>;
export const onCreateRaffle = /* GraphQL */ `subscription OnCreateRaffle($filter: ModelSubscriptionRaffleFilterInput) {
  onCreateRaffle(filter: $filter) {
    id
    type
    createdAt
    updatedAt
    raffleNonce
    ticketsAvailable
    winningBatch {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      lastTicket
      transaction {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      purchaser
      ticketsBought
      batchId
      firstTicket
      chainId
      raffle {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        ticketsAvailable
        winningBatch {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          lastTicket
          transaction {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          purchaser
          ticketsBought
          batchId
          firstTicket
          chainId
          raffle {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            ticketsAvailable
            progress
            state
            tokenId
            expires
            nftAddress
            ticketsSold
            ticketBatches
            winningTicket
            chainId
            winningAccount
            owner
            contract
            raffleWinningBatchId
            raffleReleaseTxId
            raffleOpenTxId
            raffleDrawnTxId
            raffleCloseTxId
            raffleNftId
            raffleRefundTxId
            __typename
          }
          ticketBatchTransactionId
          ticketBatchRaffleId
          __typename
        }
        releaseTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        progress
        openTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        drawnTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        state
        tokenId
        expires
        nftAddress
        ticketsSold
        ticketBatches
        winningTicket
        closeTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        chainId
        winningAccount
        owner
        contract
        nft {
          id
          type
          createdAt
          updatedAt
          contractAddress
          metadata
          tokenUri
          tokenId
          symbol
          imageUri
          tokenName
          collectionName
          lastSales
          chainId
          rarityData
          collection {
            id
            type
            contractAddress
            createdAt
            updatedAt
            symbol
            rafflesCreated
            contractDeployer
            deployedBlockNumber
            tokenType
            totalSupply
            chainId
            name
            openseaSlug
            imageUrl
            externalUrl
            discordUrl
            twitterUsername
            description
            floorPrice
            __typename
          }
          nFTCollectionId
          __typename
        }
        refundTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        raffleWinningBatchId
        raffleReleaseTxId
        raffleOpenTxId
        raffleDrawnTxId
        raffleCloseTxId
        raffleNftId
        raffleRefundTxId
        __typename
      }
      ticketBatchTransactionId
      ticketBatchRaffleId
      __typename
    }
    releaseTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    progress
    openTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    drawnTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    state
    tokenId
    expires
    nftAddress
    ticketsSold
    ticketBatches
    winningTicket
    closeTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    chainId
    winningAccount
    owner
    contract
    nft {
      id
      type
      createdAt
      updatedAt
      contractAddress
      metadata
      tokenUri
      tokenId
      symbol
      imageUri
      tokenName
      collectionName
      lastSales
      chainId
      rarityData
      collection {
        id
        type
        contractAddress
        createdAt
        updatedAt
        symbol
        rafflesCreated
        contractDeployer
        deployedBlockNumber
        tokenType
        totalSupply
        chainId
        name
        openseaSlug
        imageUrl
        externalUrl
        discordUrl
        twitterUsername
        description
        floorPrice
        __typename
      }
      nFTCollectionId
      __typename
    }
    refundTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    raffleWinningBatchId
    raffleReleaseTxId
    raffleOpenTxId
    raffleDrawnTxId
    raffleCloseTxId
    raffleNftId
    raffleRefundTxId
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnCreateRaffleSubscriptionVariables,
  APITypes.OnCreateRaffleSubscription
>;
export const onUpdateRaffle = /* GraphQL */ `subscription OnUpdateRaffle($filter: ModelSubscriptionRaffleFilterInput) {
  onUpdateRaffle(filter: $filter) {
    id
    type
    createdAt
    updatedAt
    raffleNonce
    ticketsAvailable
    winningBatch {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      lastTicket
      transaction {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      purchaser
      ticketsBought
      batchId
      firstTicket
      chainId
      raffle {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        ticketsAvailable
        winningBatch {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          lastTicket
          transaction {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          purchaser
          ticketsBought
          batchId
          firstTicket
          chainId
          raffle {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            ticketsAvailable
            progress
            state
            tokenId
            expires
            nftAddress
            ticketsSold
            ticketBatches
            winningTicket
            chainId
            winningAccount
            owner
            contract
            raffleWinningBatchId
            raffleReleaseTxId
            raffleOpenTxId
            raffleDrawnTxId
            raffleCloseTxId
            raffleNftId
            raffleRefundTxId
            __typename
          }
          ticketBatchTransactionId
          ticketBatchRaffleId
          __typename
        }
        releaseTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        progress
        openTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        drawnTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        state
        tokenId
        expires
        nftAddress
        ticketsSold
        ticketBatches
        winningTicket
        closeTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        chainId
        winningAccount
        owner
        contract
        nft {
          id
          type
          createdAt
          updatedAt
          contractAddress
          metadata
          tokenUri
          tokenId
          symbol
          imageUri
          tokenName
          collectionName
          lastSales
          chainId
          rarityData
          collection {
            id
            type
            contractAddress
            createdAt
            updatedAt
            symbol
            rafflesCreated
            contractDeployer
            deployedBlockNumber
            tokenType
            totalSupply
            chainId
            name
            openseaSlug
            imageUrl
            externalUrl
            discordUrl
            twitterUsername
            description
            floorPrice
            __typename
          }
          nFTCollectionId
          __typename
        }
        refundTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        raffleWinningBatchId
        raffleReleaseTxId
        raffleOpenTxId
        raffleDrawnTxId
        raffleCloseTxId
        raffleNftId
        raffleRefundTxId
        __typename
      }
      ticketBatchTransactionId
      ticketBatchRaffleId
      __typename
    }
    releaseTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    progress
    openTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    drawnTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    state
    tokenId
    expires
    nftAddress
    ticketsSold
    ticketBatches
    winningTicket
    closeTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    chainId
    winningAccount
    owner
    contract
    nft {
      id
      type
      createdAt
      updatedAt
      contractAddress
      metadata
      tokenUri
      tokenId
      symbol
      imageUri
      tokenName
      collectionName
      lastSales
      chainId
      rarityData
      collection {
        id
        type
        contractAddress
        createdAt
        updatedAt
        symbol
        rafflesCreated
        contractDeployer
        deployedBlockNumber
        tokenType
        totalSupply
        chainId
        name
        openseaSlug
        imageUrl
        externalUrl
        discordUrl
        twitterUsername
        description
        floorPrice
        __typename
      }
      nFTCollectionId
      __typename
    }
    refundTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    raffleWinningBatchId
    raffleReleaseTxId
    raffleOpenTxId
    raffleDrawnTxId
    raffleCloseTxId
    raffleNftId
    raffleRefundTxId
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnUpdateRaffleSubscriptionVariables,
  APITypes.OnUpdateRaffleSubscription
>;
export const onDeleteRaffle = /* GraphQL */ `subscription OnDeleteRaffle($filter: ModelSubscriptionRaffleFilterInput) {
  onDeleteRaffle(filter: $filter) {
    id
    type
    createdAt
    updatedAt
    raffleNonce
    ticketsAvailable
    winningBatch {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      lastTicket
      transaction {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        date
        eventType
        hash
        chainId
        __typename
      }
      purchaser
      ticketsBought
      batchId
      firstTicket
      chainId
      raffle {
        id
        type
        createdAt
        updatedAt
        raffleNonce
        ticketsAvailable
        winningBatch {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          lastTicket
          transaction {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            date
            eventType
            hash
            chainId
            __typename
          }
          purchaser
          ticketsBought
          batchId
          firstTicket
          chainId
          raffle {
            id
            type
            createdAt
            updatedAt
            raffleNonce
            ticketsAvailable
            progress
            state
            tokenId
            expires
            nftAddress
            ticketsSold
            ticketBatches
            winningTicket
            chainId
            winningAccount
            owner
            contract
            raffleWinningBatchId
            raffleReleaseTxId
            raffleOpenTxId
            raffleDrawnTxId
            raffleCloseTxId
            raffleNftId
            raffleRefundTxId
            __typename
          }
          ticketBatchTransactionId
          ticketBatchRaffleId
          __typename
        }
        releaseTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        progress
        openTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        drawnTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        state
        tokenId
        expires
        nftAddress
        ticketsSold
        ticketBatches
        winningTicket
        closeTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        chainId
        winningAccount
        owner
        contract
        nft {
          id
          type
          createdAt
          updatedAt
          contractAddress
          metadata
          tokenUri
          tokenId
          symbol
          imageUri
          tokenName
          collectionName
          lastSales
          chainId
          rarityData
          collection {
            id
            type
            contractAddress
            createdAt
            updatedAt
            symbol
            rafflesCreated
            contractDeployer
            deployedBlockNumber
            tokenType
            totalSupply
            chainId
            name
            openseaSlug
            imageUrl
            externalUrl
            discordUrl
            twitterUsername
            description
            floorPrice
            __typename
          }
          nFTCollectionId
          __typename
        }
        refundTx {
          id
          type
          createdAt
          updatedAt
          raffleNonce
          date
          eventType
          hash
          chainId
          __typename
        }
        raffleWinningBatchId
        raffleReleaseTxId
        raffleOpenTxId
        raffleDrawnTxId
        raffleCloseTxId
        raffleNftId
        raffleRefundTxId
        __typename
      }
      ticketBatchTransactionId
      ticketBatchRaffleId
      __typename
    }
    releaseTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    progress
    openTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    drawnTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    state
    tokenId
    expires
    nftAddress
    ticketsSold
    ticketBatches
    winningTicket
    closeTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    chainId
    winningAccount
    owner
    contract
    nft {
      id
      type
      createdAt
      updatedAt
      contractAddress
      metadata
      tokenUri
      tokenId
      symbol
      imageUri
      tokenName
      collectionName
      lastSales
      chainId
      rarityData
      collection {
        id
        type
        contractAddress
        createdAt
        updatedAt
        symbol
        rafflesCreated
        contractDeployer
        deployedBlockNumber
        tokenType
        totalSupply
        chainId
        name
        openseaSlug
        imageUrl
        externalUrl
        discordUrl
        twitterUsername
        description
        floorPrice
        __typename
      }
      nFTCollectionId
      __typename
    }
    refundTx {
      id
      type
      createdAt
      updatedAt
      raffleNonce
      date
      eventType
      hash
      chainId
      __typename
    }
    raffleWinningBatchId
    raffleReleaseTxId
    raffleOpenTxId
    raffleDrawnTxId
    raffleCloseTxId
    raffleNftId
    raffleRefundTxId
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnDeleteRaffleSubscriptionVariables,
  APITypes.OnDeleteRaffleSubscription
>;
export const onCreateNFT = /* GraphQL */ `subscription OnCreateNFT($filter: ModelSubscriptionNFTFilterInput) {
  onCreateNFT(filter: $filter) {
    id
    type
    createdAt
    updatedAt
    contractAddress
    metadata
    tokenUri
    tokenId
    symbol
    imageUri
    tokenName
    collectionName
    lastSales
    chainId
    rarityData
    collection {
      id
      type
      contractAddress
      createdAt
      updatedAt
      symbol
      rafflesCreated
      contractDeployer
      deployedBlockNumber
      tokenType
      totalSupply
      chainId
      name
      openseaSlug
      imageUrl
      externalUrl
      discordUrl
      twitterUsername
      description
      floorPrice
      __typename
    }
    nFTCollectionId
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnCreateNFTSubscriptionVariables,
  APITypes.OnCreateNFTSubscription
>;
export const onUpdateNFT = /* GraphQL */ `subscription OnUpdateNFT($filter: ModelSubscriptionNFTFilterInput) {
  onUpdateNFT(filter: $filter) {
    id
    type
    createdAt
    updatedAt
    contractAddress
    metadata
    tokenUri
    tokenId
    symbol
    imageUri
    tokenName
    collectionName
    lastSales
    chainId
    rarityData
    collection {
      id
      type
      contractAddress
      createdAt
      updatedAt
      symbol
      rafflesCreated
      contractDeployer
      deployedBlockNumber
      tokenType
      totalSupply
      chainId
      name
      openseaSlug
      imageUrl
      externalUrl
      discordUrl
      twitterUsername
      description
      floorPrice
      __typename
    }
    nFTCollectionId
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnUpdateNFTSubscriptionVariables,
  APITypes.OnUpdateNFTSubscription
>;
export const onDeleteNFT = /* GraphQL */ `subscription OnDeleteNFT($filter: ModelSubscriptionNFTFilterInput) {
  onDeleteNFT(filter: $filter) {
    id
    type
    createdAt
    updatedAt
    contractAddress
    metadata
    tokenUri
    tokenId
    symbol
    imageUri
    tokenName
    collectionName
    lastSales
    chainId
    rarityData
    collection {
      id
      type
      contractAddress
      createdAt
      updatedAt
      symbol
      rafflesCreated
      contractDeployer
      deployedBlockNumber
      tokenType
      totalSupply
      chainId
      name
      openseaSlug
      imageUrl
      externalUrl
      discordUrl
      twitterUsername
      description
      floorPrice
      __typename
    }
    nFTCollectionId
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnDeleteNFTSubscriptionVariables,
  APITypes.OnDeleteNFTSubscription
>;
export const onCreateCollection = /* GraphQL */ `subscription OnCreateCollection(
  $filter: ModelSubscriptionCollectionFilterInput
) {
  onCreateCollection(filter: $filter) {
    id
    type
    contractAddress
    createdAt
    updatedAt
    symbol
    rafflesCreated
    contractDeployer
    deployedBlockNumber
    tokenType
    totalSupply
    chainId
    name
    openseaSlug
    imageUrl
    externalUrl
    discordUrl
    twitterUsername
    description
    floorPrice
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnCreateCollectionSubscriptionVariables,
  APITypes.OnCreateCollectionSubscription
>;
export const onUpdateCollection = /* GraphQL */ `subscription OnUpdateCollection(
  $filter: ModelSubscriptionCollectionFilterInput
) {
  onUpdateCollection(filter: $filter) {
    id
    type
    contractAddress
    createdAt
    updatedAt
    symbol
    rafflesCreated
    contractDeployer
    deployedBlockNumber
    tokenType
    totalSupply
    chainId
    name
    openseaSlug
    imageUrl
    externalUrl
    discordUrl
    twitterUsername
    description
    floorPrice
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnUpdateCollectionSubscriptionVariables,
  APITypes.OnUpdateCollectionSubscription
>;
export const onDeleteCollection = /* GraphQL */ `subscription OnDeleteCollection(
  $filter: ModelSubscriptionCollectionFilterInput
) {
  onDeleteCollection(filter: $filter) {
    id
    type
    contractAddress
    createdAt
    updatedAt
    symbol
    rafflesCreated
    contractDeployer
    deployedBlockNumber
    tokenType
    totalSupply
    chainId
    name
    openseaSlug
    imageUrl
    externalUrl
    discordUrl
    twitterUsername
    description
    floorPrice
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnDeleteCollectionSubscriptionVariables,
  APITypes.OnDeleteCollectionSubscription
>;
export const onCreateAccount = /* GraphQL */ `subscription OnCreateAccount($filter: ModelSubscriptionAccountFilterInput) {
  onCreateAccount(filter: $filter) {
    id
    type
    createdAt
    updatedAt
    address
    rafflesCreated
    rafflesWon
    rafflesEntered
    ticketsBought
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnCreateAccountSubscriptionVariables,
  APITypes.OnCreateAccountSubscription
>;
export const onUpdateAccount = /* GraphQL */ `subscription OnUpdateAccount($filter: ModelSubscriptionAccountFilterInput) {
  onUpdateAccount(filter: $filter) {
    id
    type
    createdAt
    updatedAt
    address
    rafflesCreated
    rafflesWon
    rafflesEntered
    ticketsBought
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnUpdateAccountSubscriptionVariables,
  APITypes.OnUpdateAccountSubscription
>;
export const onDeleteAccount = /* GraphQL */ `subscription OnDeleteAccount($filter: ModelSubscriptionAccountFilterInput) {
  onDeleteAccount(filter: $filter) {
    id
    type
    createdAt
    updatedAt
    address
    rafflesCreated
    rafflesWon
    rafflesEntered
    ticketsBought
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnDeleteAccountSubscriptionVariables,
  APITypes.OnDeleteAccountSubscription
>;
