type TicketRefund
  @model
  @auth(
    rules: [
      { allow: public, operations: [read] }
      { allow: public, provider: iam, operations: [read, create, update] }
    ]
  ) {
  id: ID!
  type: String!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  raffleNonce: Int!
  ethAmount: Float
  refundee: String
  chainId: String!
  raffle: Raffle @hasOne
  tx: Transaction @hasOne
}

type Stat
  @model
  @auth(
    rules: [
      { allow: public, operations: [read] }
      { allow: public, provider: iam, operations: [read, create, update] }
    ]
  ) {
  id: ID!
  type: String!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  ethPaid: Float
  ticketsBought: Int
  royaltiesPaid: Float
  chainId: String!
  rafflesCreated: Int
}

type TicketBatch
  @searchable
  @model
  @auth(
    rules: [
      { allow: public, operations: [read] }
      { allow: public, provider: iam, operations: [read, create, update] }
    ]
  ) {
  id: ID!
  type: String!
    @index(
      name: "ticketBatchesByCreatedAt"
      queryField: "ticketBatchesByCreatedAt"
      sortKeyFields: ["createdAt"]
    )
    @index(
      name: "ticketBatchesByUpdatedAt"
      queryField: "ticketBatchesByUpdatedAt"
      sortKeyFields: ["updatedAt"]
    )
    @index(
      name: "ticketBatchesByTicketsBought"
      queryField: "ticketBatchesByTicketsBought"
      sortKeyFields: ["ticketsBought"]
    )
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  raffleNonce: Int!
  lastTicket: Int!
  transaction: Transaction! @hasOne
  purchaser: String!
  ticketsBought: Int!
  batchId: Int!
  firstTicket: Int!
  chainId: String!
  raffle: Raffle! @belongsTo
}

type Transaction
  @model
  @auth(
    rules: [
      { allow: public, operations: [read] }
      { allow: public, provider: iam, operations: [read, create, update] }
    ]
  ) {
  id: ID!
  type: String!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  raffleNonce: Int!
  date: AWSDateTime!
  eventType: Int!
  hash: String!
  chainId: String!
}

type Raffle
  @model
  @searchable
  @auth(
    rules: [
      { allow: public, operations: [read] }
      { allow: public, provider: iam, operations: [read, create, update] }
    ]
  ) {
  id: ID!
  type: String!
    @index(
      name: "rafflesByCreatedAt"
      queryField: "rafflesByCreatedAt"
      sortKeyFields: ["createdAt"]
    )
    @index(
      name: "rafflesByUpdatedAt"
      queryField: "rafflesByUpdatedAt"
      sortKeyFields: ["updatedAt"]
    )
    @index(
      name: "rafflesByProgress"
      queryField: "rafflesByProgress"
      sortKeyFields: ["progress"]
    )
    @index(
      name: "rafflesByTicketsAvailable"
      queryField: "rafflesByTicketsAvailable"
      sortKeyFields: ["ticketsAvailable"]
    )
    @index(
      name: "rafflesByExpires"
      queryField: "rafflesByExpires"
      sortKeyFields: ["expires"]
    )
    @index(
      name: "rafflesByTicketsSold"
      queryField: "rafflesByTicketsSold"
      sortKeyFields: ["ticketsSold"]
    )
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  raffleNonce: Int!
  ticketsAvailable: Int!
  winningBatch: TicketBatch @hasOne
  releaseTx: Transaction @hasOne
  progress: Float!
  openTx: Transaction @hasOne
  drawnTx: Transaction @hasOne
  state: Int!
  tokenId: String!
  expires: AWSDateTime!
  nftAddress: String!
  ticketsSold: Int!
  ticketBatches: Int
  winningTicket: Int
  closeTx: Transaction @hasOne
  chainId: String!
  winningAccount: String
  owner: String!
  contract: String!
  nft: NFT! @hasOne
  refundTx: Transaction @hasOne
}

type NFT
  @model
  @auth(
    rules: [
      { allow: public, operations: [read] }
      { allow: public, provider: iam, operations: [read, create, update] }
    ]
  ) {
  id: ID!
  type: String!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  contractAddress: String!
  metadata: AWSJSON!
  tokenUri: String
  tokenId: String!
  symbol: String
  imageUri: String
  tokenName: String!
  collectionName: String!
  lastSales: AWSJSON
  chainId: String!
  rarityData: AWSJSON
  animationUrl: String
  collection: Collection! @hasOne
}

type Collection
  @model
  @auth(
    rules: [
      { allow: public, operations: [read] }
      { allow: public, provider: iam, operations: [read, create, update] }
    ]
  ) {
  id: ID!
  type: String!
  contractAddress: String!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  symbol: String
  rafflesCreated: Int
  contractDeployer: String
  deployedBlockNumber: Int
  tokenType: String!
  totalSupply: String
  chainId: String!
  name: String!
  openseaSlug: String
  imageUrl: String
  externalUrl: String
  discordUrl: String
  twitterUsername: String
  description: String
  floorPrice: Float
}

type Account
  @model
  @searchable
  @auth(
    rules: [
      { allow: public, operations: [read] }
      { allow: public, provider: iam, operations: [read, create, update] }
    ]
  ) {
  id: ID!
  type: String!
    @index(
      name: "accountsByTicketsBought"
      queryField: "accountsByTicketsBought"
      sortKeyFields: ["ticketsBought"]
    )
    @index(
      name: "accountsByRafflesEntered"
      queryField: "accountsByRafflesEntered"
      sortKeyFields: ["rafflesEntered"]
    )
    @index(
      name: "accountsByRafflesWon"
      queryField: "accountsByRafflesWon"
      sortKeyFields: ["rafflesWon"]
    )
    @index(
      name: "accountsByRafflesCreated"
      queryField: "accountsByRafflesCreated"
      sortKeyFields: ["rafflesCreated"]
    )
    @index(
      name: "accountsByUpdatedAt"
      queryField: "accountsByUpdatedAt"
      sortKeyFields: ["updatedAt"]
    )
    @index(
      name: "accountsByCreatedAt"
      queryField: "accountsByCreatedAt"
      sortKeyFields: ["createdAt"]
    )
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  address: String!
  rafflesCreated: Int!
  rafflesWon: Int!
  rafflesEntered: Int!
  ticketsBought: Int!
}